[workspace]
resolver = "2"

members = [
    "api/lambda-common-ping",
    "api/lambda-ws-connect",
    "api/lambda-ws-disconnect",
    "api/core",
    "logic",
    "logic/binary-encoding",
    "logic/messages-macro"
]
