[package]
name = "logic-binding-cpp"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "staticlib" ]
name = "logic"

[dependencies]
uniffi = { version = "0.28.1" }

[build-dependencies]
uniffi = { version = "0.28.1", features = [ "build" ] }
