[package]
name = "messages-macro"
version = "0.0.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
proc-macro2 = "1.0.87"
quote = "1.0.37"
syn = "2.0.79"
binary-encoding = { path = "../binary-encoding" }

[lib]
proc-macro = true
