[package]
name = "messages-macro"
version = "0.0.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.77"

[dev-dependencies]
serde_json = "1.0"

[lib]
proc-macro = true
