[package]
name = "logic"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
messages-macro = { path = "messages-macro" }
time = "0.3.36"
