name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  
  merge_group:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: cache-cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cargo-linux-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-linux
    - uses: aws-actions/configure-aws-credentials@v4
      if: github.actor != 'dependabot[bot]' # Dependabot doesn't have access to secrets, skip this step
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - run: ./run.sh deps
    - run: ./run.sh build
    - run: ./run.sh test
    - run: ./run.sh lint
